#################################################################
# +-----------------------------------------------------------+ #
# |                        EcoNexusLite                       | #
# |                        By MikesLab                        | #
# +-----------------------------------------------------------+ #
#################################################################

#################################################################
# ----------------------- Donations <3 ------------------------ #
# ------------------- donation.mikeslab.it -------------------- #
#################################################################

#################################################################
#                         Documentation                         #
#                https://econexuslite.mikeslab.it               #
#################################################################

settings:
  debug-mode: false
  mongo-logging: false
# Follow the instructions on the documentation to set up the database
database:
  type: JSON # SQL, JSON or MONGODB
  uri: "{dataFolder}/bank.json"
  password: ""
  username: ""
  database: ""
  table: ""